# fly.toml app configuration file generated for reminderbot85 on 2023-07-14T14:39:04+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reminderbot85"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
